# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuzu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.stackedWidget.setMaximumSize(QtCore.QSize(1280, 720))
        self.stackedWidget.setStyleSheet("background-color: rgb(162, 162, 162);\n"
"")
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.ana_sayfa = QtWidgets.QWidget()
        self.ana_sayfa.setObjectName("ana_sayfa")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ana_sayfa)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.ana_sayfa)
        self.label_2.setMinimumSize(QtCore.QSize(1000, 100))
        self.label_2.setMaximumSize(QtCore.QSize(1000, 100))
        self.label_2.setStyleSheet("font-size:32px;\n"
"color:red;\n"
"letter-spacing:2px;\n"
"padding: 0 0 0 380px;\n"
"background-color: rgb(54, 232, 221);\n"
"border: 2px solid red;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.buton_oyna = QtWidgets.QPushButton(self.ana_sayfa)
        self.buton_oyna.setMinimumSize(QtCore.QSize(300, 100))
        self.buton_oyna.setMaximumSize(QtCore.QSize(300, 100))
        self.buton_oyna.setStyleSheet("QPushButton{\n"
"color: red;\n"
"font-size:32px;\n"
"background-color: rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:red;\n"
"color:rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}")
        self.buton_oyna.setObjectName("buton_oyna")
        self.horizontalLayout_4.addWidget(self.buton_oyna)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.buton_ayarlar = QtWidgets.QPushButton(self.ana_sayfa)
        self.buton_ayarlar.setMinimumSize(QtCore.QSize(300, 100))
        self.buton_ayarlar.setMaximumSize(QtCore.QSize(300, 100))
        self.buton_ayarlar.setStyleSheet("QPushButton{\n"
"color: red;\n"
"font-size:32px;\n"
"background-color: rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:red;\n"
"color:rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}")
        self.buton_ayarlar.setObjectName("buton_ayarlar")
        self.horizontalLayout_3.addWidget(self.buton_ayarlar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.buton_emek = QtWidgets.QPushButton(self.ana_sayfa)
        self.buton_emek.setMinimumSize(QtCore.QSize(300, 100))
        self.buton_emek.setMaximumSize(QtCore.QSize(300, 100))
        self.buton_emek.setStyleSheet("QPushButton{\n"
"color: red;\n"
"font-size:32px;\n"
"background-color: rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:red;\n"
"color:rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}")
        self.buton_emek.setObjectName("buton_emek")
        self.horizontalLayout_2.addWidget(self.buton_emek)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.buton_cikis = QtWidgets.QPushButton(self.ana_sayfa)
        self.buton_cikis.setMinimumSize(QtCore.QSize(200, 100))
        self.buton_cikis.setMaximumSize(QtCore.QSize(200, 100))
        self.buton_cikis.setStyleSheet("QPushButton{\n"
"color: red;\n"
"font-size:32px;\n"
"background-color: rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:red;\n"
"color:rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}")
        self.buton_cikis.setObjectName("buton_cikis")
        self.horizontalLayout.addWidget(self.buton_cikis)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.stackedWidget.addWidget(self.ana_sayfa)
        self.oyun_sayfasi = QtWidgets.QWidget()
        self.oyun_sayfasi.setObjectName("oyun_sayfasi")
        self.buton_tikla = QtWidgets.QPushButton(self.oyun_sayfasi)
        self.buton_tikla.setGeometry(QtCore.QRect(590, 310, 50, 50))
        self.buton_tikla.setStyleSheet("QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: red;\n"
"    border: 2px dashed red;\n"
"    border-radius: 25px;\n"
"    padding: 5px;\n"
"    background-color:rgb(54, 232, 221);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(54, 232, 221);\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:red;\n"
"    color:rgb(54, 232, 221);\n"
"    border: 2px dashed rgb(54, 232, 221);;\n"
"}")
        self.buton_tikla.setObjectName("buton_tikla")
        self.tiklanma_sayisi = QtWidgets.QLabel(self.oyun_sayfasi)
        self.tiklanma_sayisi.setGeometry(QtCore.QRect(0, 0, 200, 30))
        self.tiklanma_sayisi.setMinimumSize(QtCore.QSize(200, 30))
        self.tiklanma_sayisi.setMaximumSize(QtCore.QSize(200, 30))
        self.tiklanma_sayisi.setStyleSheet("color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);\n"
"padding-left:5px;\n"
"border: 2px solid red;")
        self.tiklanma_sayisi.setObjectName("tiklanma_sayisi")
        self.zaman_etiket = QtWidgets.QLabel(self.oyun_sayfasi)
        self.zaman_etiket.setGeometry(QtCore.QRect(1080, 0, 200, 30))
        self.zaman_etiket.setMinimumSize(QtCore.QSize(200, 30))
        self.zaman_etiket.setMaximumSize(QtCore.QSize(200, 30))
        self.zaman_etiket.setStyleSheet("color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);\n"
"padding-left:5px;\n"
"border: 2px solid red;")
        self.zaman_etiket.setObjectName("zaman_etiket")
        self.stackedWidget.addWidget(self.oyun_sayfasi)
        self.ayar_sayfasi = QtWidgets.QWidget()
        self.ayar_sayfasi.setObjectName("ayar_sayfasi")
        self.label_4 = QtWidgets.QLabel(self.ayar_sayfasi)
        self.label_4.setGeometry(QtCore.QRect(131, 63, 1000, 100))
        self.label_4.setMinimumSize(QtCore.QSize(1000, 100))
        self.label_4.setMaximumSize(QtCore.QSize(1000, 100))
        self.label_4.setStyleSheet("font-size:32px;\n"
"color:red;\n"
"letter-spacing:2px;\n"
"padding: 0 0 0 380px;\n"
"background-color: rgb(54, 232, 221);\n"
"border: 2px solid red;")
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(self.ayar_sayfasi)
        self.layoutWidget.setGeometry(QtCore.QRect(400, 660, 412, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.buton_degisiklikleri_kaydet = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buton_degisiklikleri_kaydet.sizePolicy().hasHeightForWidth())
        self.buton_degisiklikleri_kaydet.setSizePolicy(sizePolicy)
        self.buton_degisiklikleri_kaydet.setMinimumSize(QtCore.QSize(200, 50))
        self.buton_degisiklikleri_kaydet.setMaximumSize(QtCore.QSize(200, 50))
        self.buton_degisiklikleri_kaydet.setStyleSheet("QPushButton{\n"
"color: red;\n"
"font-size:16px;\n"
"background-color: rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:red;\n"
"color:rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.buton_degisiklikleri_kaydet.setObjectName("buton_degisiklikleri_kaydet")
        self.horizontalLayout_11.addWidget(self.buton_degisiklikleri_kaydet)
        self.buton_ayar_dan_menu = QtWidgets.QPushButton(self.layoutWidget)
        self.buton_ayar_dan_menu.setMinimumSize(QtCore.QSize(200, 50))
        self.buton_ayar_dan_menu.setMaximumSize(QtCore.QSize(200, 50))
        self.buton_ayar_dan_menu.setStyleSheet("QPushButton{\n"
"color: red;\n"
"font-size:16px;\n"
"background-color: rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:red;\n"
"color:rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}")
        self.buton_ayar_dan_menu.setObjectName("buton_ayar_dan_menu")
        self.horizontalLayout_11.addWidget(self.buton_ayar_dan_menu)
        self.line = QtWidgets.QFrame(self.ayar_sayfasi)
        self.line.setGeometry(QtCore.QRect(-40, 170, 1501, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget1 = QtWidgets.QWidget(self.ayar_sayfasi)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 440, 581, 171))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setMinimumSize(QtCore.QSize(300, 100))
        self.label_7.setMaximumSize(QtCore.QSize(300, 100))
        self.label_7.setStyleSheet("color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border: 2px solid red;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(280, 25))
        self.label_3.setMaximumSize(QtCore.QSize(280, 25))
        self.label_3.setStyleSheet("color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);\n"
"padding-left:5px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.comboBox_Dil = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Dil.sizePolicy().hasHeightForWidth())
        self.comboBox_Dil.setSizePolicy(sizePolicy)
        self.comboBox_Dil.setMinimumSize(QtCore.QSize(280, 25))
        self.comboBox_Dil.setMaximumSize(QtCore.QSize(280, 25))
        self.comboBox_Dil.setStyleSheet("color:red;\n"
"background-color:rgb(54, 232, 221);")
        self.comboBox_Dil.setObjectName("comboBox_Dil")
        self.comboBox_Dil.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_Dil)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.layoutWidget2 = QtWidgets.QWidget(self.ayar_sayfasi)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 180, 574, 231))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setMinimumSize(QtCore.QSize(300, 100))
        self.label_6.setMaximumSize(QtCore.QSize(300, 100))
        self.label_6.setStyleSheet("font-size:16px;\n"
"color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);\n"
"border: 2px solid red;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setMinimumSize(QtCore.QSize(280, 25))
        self.label.setMaximumSize(QtCore.QSize(280, 25))
        self.label.setStyleSheet("color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);\n"
"padding-left:5px;")
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.comboBox_ekran_cozunurluk = QtWidgets.QComboBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_ekran_cozunurluk.sizePolicy().hasHeightForWidth())
        self.comboBox_ekran_cozunurluk.setSizePolicy(sizePolicy)
        self.comboBox_ekran_cozunurluk.setMinimumSize(QtCore.QSize(280, 25))
        self.comboBox_ekran_cozunurluk.setMaximumSize(QtCore.QSize(280, 25))
        self.comboBox_ekran_cozunurluk.setStyleSheet("color:red;\n"
"background-color:rgb(54, 232, 221);")
        self.comboBox_ekran_cozunurluk.setObjectName("comboBox_ekran_cozunurluk")
        self.horizontalLayout_7.addWidget(self.comboBox_ekran_cozunurluk)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.layoutWidget3 = QtWidgets.QWidget(self.ayar_sayfasi)
        self.layoutWidget3.setGeometry(QtCore.QRect(610, 440, 574, 171))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem14)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_12.setMinimumSize(QtCore.QSize(300, 100))
        self.label_12.setMaximumSize(QtCore.QSize(300, 100))
        self.label_12.setStyleSheet("color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border: 2px solid red;")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem15)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_17.setSpacing(10)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_13.setMinimumSize(QtCore.QSize(280, 25))
        self.label_13.setMaximumSize(QtCore.QSize(280, 25))
        self.label_13.setStyleSheet("color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);\n"
"padding-left:5px;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.comboBox_ayar = QtWidgets.QComboBox(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_ayar.sizePolicy().hasHeightForWidth())
        self.comboBox_ayar.setSizePolicy(sizePolicy)
        self.comboBox_ayar.setMinimumSize(QtCore.QSize(280, 25))
        self.comboBox_ayar.setMaximumSize(QtCore.QSize(280, 25))
        self.comboBox_ayar.setStyleSheet("color:red;\n"
"background-color:rgb(54, 232, 221);")
        self.comboBox_ayar.setObjectName("comboBox_ayar")
        self.comboBox_ayar.addItem("")
        self.horizontalLayout_17.addWidget(self.comboBox_ayar)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.layoutWidget4 = QtWidgets.QWidget(self.ayar_sayfasi)
        self.layoutWidget4.setGeometry(QtCore.QRect(610, 180, 574, 231))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_15.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_15.setSpacing(5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem16)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_11.setMinimumSize(QtCore.QSize(300, 100))
        self.label_11.setMaximumSize(QtCore.QSize(300, 100))
        self.label_11.setStyleSheet("font-size:16px;\n"
"color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);\n"
"border: 2px solid red;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem17)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        spacerItem18 = QtWidgets.QSpacerItem(40, 15, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem18)
        self.checkBox_muzik = QtWidgets.QCheckBox(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_muzik.sizePolicy().hasHeightForWidth())
        self.checkBox_muzik.setSizePolicy(sizePolicy)
        self.checkBox_muzik.setMinimumSize(QtCore.QSize(570, 25))
        self.checkBox_muzik.setMaximumSize(QtCore.QSize(1312, 25))
        self.checkBox_muzik.setStyleSheet("font-size:16px;\n"
"color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);\n"
"padding-left:50px;")
        self.checkBox_muzik.setObjectName("checkBox_muzik")
        self.verticalLayout_9.addWidget(self.checkBox_muzik)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.line_4 = QtWidgets.QFrame(self.ayar_sayfasi)
        self.line_4.setGeometry(QtCore.QRect(-120, 630, 1471, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_2 = QtWidgets.QFrame(self.ayar_sayfasi)
        self.line_2.setGeometry(QtCore.QRect(-93, 420, 1461, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.ayar_sayfasi)
        self.line_3.setGeometry(QtCore.QRect(590, 180, 16, 451))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.stackedWidget.addWidget(self.ayar_sayfasi)
        self.emek_sayfasi = QtWidgets.QWidget()
        self.emek_sayfasi.setObjectName("emek_sayfasi")
        self.label_5 = QtWidgets.QLabel(self.emek_sayfasi)
        self.label_5.setGeometry(QtCore.QRect(131, 63, 1000, 100))
        self.label_5.setMinimumSize(QtCore.QSize(1000, 100))
        self.label_5.setMaximumSize(QtCore.QSize(100000, 100))
        self.label_5.setStyleSheet("font-size:32px;\n"
"color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);\n"
"border: 2px solid red;")
        self.label_5.setObjectName("label_5")
        self.line_6 = QtWidgets.QFrame(self.emek_sayfasi)
        self.line_6.setGeometry(QtCore.QRect(-40, 170, 1371, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.emek_receb = QtWidgets.QLabel(self.emek_sayfasi)
        self.emek_receb.setGeometry(QtCore.QRect(380, 720, 500, 100))
        self.emek_receb.setMinimumSize(QtCore.QSize(500, 100))
        self.emek_receb.setMaximumSize(QtCore.QSize(500, 100))
        self.emek_receb.setStyleSheet("font-size:32px;\n"
"color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);")
        self.emek_receb.setObjectName("emek_receb")
        self.buton_emek_den_menu = QtWidgets.QPushButton(self.emek_sayfasi)
        self.buton_emek_den_menu.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.buton_emek_den_menu.setMinimumSize(QtCore.QSize(50, 50))
        self.buton_emek_den_menu.setMaximumSize(QtCore.QSize(50, 50))
        self.buton_emek_den_menu.setStyleSheet("QPushButton{\n"
"color: red;\n"
"font-size:16px;\n"
"background-color: rgb(54, 232, 221); \n"
"border-radius: 25px;\n"
"border: 2px solid red;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:red;\n"
"color:rgb(54, 232, 221);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"\n"
"")
        self.buton_emek_den_menu.setObjectName("buton_emek_den_menu")
        self.label_8 = QtWidgets.QLabel(self.emek_sayfasi)
        self.label_8.setGeometry(QtCore.QRect(230, 240, 800, 100))
        self.label_8.setMinimumSize(QtCore.QSize(800, 100))
        self.label_8.setMaximumSize(QtCore.QSize(800, 100))
        self.label_8.setStyleSheet("font-size:32px;\n"
"color:red;\n"
"letter-spacing:2px;\n"
"background-color: rgb(54, 232, 221);\n"
"border: 2px solid red;")
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.emek_sayfasi)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "tıkLA"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">ANA MENÜ</span></p></body></html>"))
        self.buton_oyna.setToolTip(_translate("MainWindow", "<html><head/><body><p>Oyuna başlamak için tıkLA</p></body></html>"))
        self.buton_oyna.setText(_translate("MainWindow", "Oyna"))
        self.buton_ayarlar.setText(_translate("MainWindow", "Ayarlar"))
        self.buton_emek.setText(_translate("MainWindow", "Emeği Geçenler"))
        self.buton_cikis.setText(_translate("MainWindow", "Çıkış"))
        self.buton_tikla.setText(_translate("MainWindow", "Tıkla"))
        self.tiklanma_sayisi.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Tıklanma Sayısı </span><span style=\" font-size:16pt;\">:</span></p></body></html>"))
        self.zaman_etiket.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Zaman </span><span style=\" font-size:16pt;\">:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>AYARLAR <span style=\" font-weight:600; font-style:italic; text-decoration: underline;\">Aktif Değil</span></p></body></html>"))
        self.buton_degisiklikleri_kaydet.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.buton_degisiklikleri_kaydet.setText(_translate("MainWindow", "Değişiklikleri Kaydet"))
        self.buton_ayar_dan_menu.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.buton_ayar_dan_menu.setText(_translate("MainWindow", "Ana Menü"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Dil Ayarları</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Dil :</span></p></body></html>"))
        self.comboBox_Dil.setItemText(0, _translate("MainWindow", "Türkçe"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Görüntü Ayarları</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Ekran Çözünürlüğü </span><span style=\" font-size:16pt;\">:</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Dil Ayarları</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Dil :</span></p></body></html>"))
        self.comboBox_ayar.setItemText(0, _translate("MainWindow", "Türkçe"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Ses Ayarları</span></p></body></html>"))
        self.checkBox_muzik.setText(_translate("MainWindow", "Müzik"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Emeği Geçenler</p></body></html>"))
        self.emek_receb.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Receb BAL</p></body></html>"))
        self.buton_emek_den_menu.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.buton_emek_den_menu.setText(_translate("MainWindow", "<--"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Receb BAL</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
